# Generated by Django 4.0.4 on 2022-05-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tag_profile_website_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Majlis',
        ),
    ]
