# Generated by Django 4.0.4 on 2022-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_course_majlis'),
    ]

    operations = [
        migrations.AddField(
            model_name='majlis',
            name='people',
            field=models.ManyToManyField(related_name='people', to='accounts.profile'),
        ),
    ]
