# Generated by Django 4.0.4 on 2022-05-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_body_majlis_description_remove_majlis_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majlis',
            name='author',
        ),
    ]
