# Generated by Django 4.0.4 on 2022-05-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_majlis_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majlis',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='majlis',
            name='published',
        ),
        migrations.RemoveField(
            model_name='majlis',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='majlis',
            name='tags',
        ),
    ]
