# Generated by Django 4.0.4 on 2022-05-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_majlis_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majlis',
            name='people',
        ),
        migrations.AlterField(
            model_name='majlis',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
