# Generated by Django 4.0.4 on 2022-05-29 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_majlis_author_majlis_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majlis',
            name='people',
            field=models.ManyToManyField(related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
